<header id="site-header" class="site-header">
  <div class="header-top">
    <div class="menu">
      <ul>
        <li><a href="#">Water Management</a></li>
        <li><a href="#">Crescent Services</a></li>
        <li class="active"><a href="#">Ameriflow</a></li>
        <li><a href="#">SJB</a></li>
      </ul>
    </div>
  </div>
  <div class="header-bottom">
    <div class="site-container">
      <div class="logo"><a href="#"><img src="theme/images/logo.png" alt=""/></a></div>
      <div class="login-btn">
        <a class="btn" href="#">EnviroEdge</a>
      </div>
      <div class="hamburger-wrapper">
      <a href="#" class="hamburger"></a>
      </div>
      <nav class="nav">
        <ul class="menu">
          <li class="active"><a href="#">Flowback</a></li>
          <li><a href="#">Rentals</a></li>
          <li><a href="#">Contact</a></li>
          <li><a href="#">Blog</a></li>
        </ul>
      </nav>
    </div>
  </div>
</header>